on: [push]

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: docker build . -t tipsandtrickscontainerregistry.azurecr.io/tipsandtrickscontainer:${{ github.sha }}
      
    - uses: Azure/container-scan@v0
      id: container-scan
      continue-on-error: true
      with:
        image-name: tipsandtrickscontainerregistry.azurecr.io/tipsandtrickscontainer:${{ github.sha }}
    
    - uses: Azure/docker-login@v1
      with:
        login-server: tipsandtrickscontainerregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: docker push tipsandtrickscontainerregistry.azurecr.io/tipsandtrickscontainer:${{ github.sha }}       

    - name: Post logs to appinsights
      uses: Azure/publish-security-assessments@v0
      with: 
        scan-results-path: ${{ steps.container-scan.outputs.scan-report-path }}
        connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
        subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }} 
        # connection-string: InstrumentationKey=2117c02e-80c3-47af-b1c5-768529add990;IngestionEndpoint=https://westeurope-4.in.applicationinsights.azure.com/
        # subscription-token: c7999d44-c30a-4f05-b88f-a9bc82897a2a.71ed082a-0cea-4401-9b9f-64c5c7bc367d



        
                           