# This is a basic workflow to help you get started with Actions

name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ACR build
        id: acr
        uses: ams0/acr-task-github-action@v2
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: ${{ secrets.registry }}
          repository: ${{ secrets.repository }}         
          # service_principal: "bfb6b0f2-5e8f-497f-9101-43a10711a63b"
          # service_principal_password: "fvBbL99FVWbyWbnALkeTTvmo9ar0~h7Z8t"
          # tenant: "85fff789-2a94-4cbc-9704-10390cf69733"
          # registry: "tipsandtrickscontainerregistry"
          # repository: "tipsandtrickscontainer"                               